### PR TITLE
Add support for showing absolute ETA

### PR DESCRIPTION
**Pull request by mmirate**
i.e. instead of the estimated amount of time remaining in the print, this is the datetime at which the print is estimated to finish.

Also, while I was at it, I put the status-embed's filename field inside backticks, so that filenames containing double underscores don't get mangled by Discord's Markdown interpretation.

### CODE REVIEW

**Comment by mmirate** [comment]
```
___________________________________ summary ____________________________________
ERROR:   py27: could not install deps [git+https://github.com/foosel/OctoPrint.git@1.3.12, -rrequirements.txt, -rrequirements-dev.txt]; v = InvocationError('/root/repo/.tox/py27/bin/python -m pip install git+https://github.com/foosel/OctoPrint.git@1.3.12 -rrequirements.txt -rrequirements-dev.txt', 1)
  py37: commands succeeded
```

FYI, your CI appears to have some pre-existing problems. Though, since Python 2 has been unsupported for awhile by Octoprint (let alone by the Python upstream themselves), I think this is trivially fixable by removing Python 2 from this project's testing matrix.

**Comment by cameroncros** [comment]
Yup, the py27 testing is pretty much pointless, will remove in the future.
I will try review this PR soon, thanks for the contribution.

**Review by cameroncros — APPROVED** [review]

**Comment by cameroncros** [comment]
Sorry for the delay, but I have now merged this. Thank you for your contribution.

**Comment by mmirate** [comment]
You're welcome! 😃

**Pull request merged**
