### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vfrdirk**
Added instructions for finding the correct User ID which confounded me until I found a resolved GitHub issue.

### CODE REVIEW

**Review by cameroncros — APPROVED** [review]

**Comment by cameroncros** [comment]
Thank you for the PR, the instructions are hard to write when I am not aware of the common pitfalls, so updates like these are greatly appreciated.

**Comment by vfrdirk** [comment]
Sure. I've got another one inbound that links to the Wiki page I started. I've seen people asking about what commands are available, which is evident after a /help, but is messy if you're trying to restrict a specific user to non-harmful commands.

**Comment by cameroncros** [comment]
I am not sure how wikis work in GitHub, but do you want access so you can add info to this repos wiki?

**Comment by vfrdirk** [comment]
GitHub wikis are, by default, configured to be created and edited by any github user. You can change this to 'collaborators only' in settings. So, for now, I already have the page created and am testing what I plan to put into the README. If you decide to tighten security on the Wiki, then I'd say add me. Really fun plugin, though, thanks!

**Pull request merged**
