### PR TITLE
Add custom embed support

### LINKED ISSUE #117: Ability to @ users and roles not working
I've been trying to @ users and roles within the various configurable messages and it doesn't seem to work when entering any of the following values:
```
@UserName
@UserID
@UserNickname
@RoleName
@RoleID
```

I would really only expect the User/Role IDs above to work, but none work currently. I'd appreciate any assistance with this so I can alert a role when a job has completed.

### PR DESCRIPTION
**Pull request by wchill**
image

Closes #117 #129

### CODE REVIEW

**Comment by wchill** [comment]
image

the settings page

**Comment by cameroncros** [comment]
I havent looked too deeply, but based on the screenshot this looks fantastic. I will do my best to get this reviewed and merged ASAP, Thank you for your contribution!

**Comment by cameroncros** [comment]
Okay, I am happy with it, except that the unit tests do not pass, and there is effectively no tests for your code. I will merge and fix the tests that are broken

**Comment by wchill** [comment]
I think CircleCI was already failing before I started working on this, so I just assumed tests were already broken. /shrug

**Comment by cameroncros** [comment]
Yeah, they kinda are broken constantly, so thats fair enough

**Pull request merged**
