### PR TITLE
Add Hostname Masking

### PR DESCRIPTION
**Pull request by shaynemk**
Simple changes to allow for a user configurable hostname to be shown instead of IP addresses, useful for public discord channels or utilizing reverse proxies. I've got a few more things I would like to implement, but made the PR so we can get the basic functionality out there. This should satisfy the request in #88.

### CODE REVIEW

**Comment by shaynemk** [comment]
Looks like the check failed because it couldn't run virtualenv. Also, didn't realize that the last commit would fall into this PR as well, but it's just for adding timelapse event support.

**Comment by shaynemk** [comment]
Reverted the branch back to the basics, noticed a weird bug after the timelapse event setup...also found out some git magic to fix it.

**Comment by cameroncros** [comment]
Thanks for this, looks pretty good on the surface, I will test it when I am home and merge and release it shortly.

**Comment by cameroncros** [comment]
Sorry for the delay with merging this, i really wanted to get it tested and checked faster than this. Thank you for your contribution.

**Comment by cameroncros** [comment]
I have merged and released your code, but I changed a fair bit of it, to make it a bit clearer how it works. I hope this doesn't break anything on your end.

**Pull request merged**
